version: '3.8'

services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    container_name: api
    environment:
      - ENV=${ENV}
      - API_PORT=${API_PORT}
      - DB_HOST=${DB_HOST}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_NAME=${DB_NAME}
      - DB_PORT=${DB_PORT}
    depends_on:
      - db
    ports:
      - "${API_PORT}:${API_PORT}"
    volumes:
      - .:/app
      - /app/node_modules

  db:
    container_name: mysql
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_NAME}
    ports:
      - "${DB_PORT}:${DB_PORT}"
    volumes:
      - mysql-data:/var/lib/mysql

  adminer:
    image: adminer
    container_name: adminer
    ports:
      - "${ADMINER_PORT}:${ADMINER_PORT}"
    environment:
      ADMINER_DEFAULT_SERVER: db
    depends_on:
      - db

volumes:
  mysql-data:
